### ISSUE TITLE
Improve responsiveness 

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#143]
The app is currently not responsive. We could integrate a grid system tied to common screen sizes via media queries. For instance on smaller screens the boards would be displayed as 1-2 columns and multiple rows preventing the plots from being squished.

**Comment by ivokwee** [comment]
Yes. We should go towards a responsive layout. Also responsive towards bigger screens is of importance. Everything on one page without scrolling was a design choice. We thought it was better to have multiple tabs rather than scrolling down. I definitely want to go mobile. But keep in mind that perhaps mobile might need a completely different UI if necessary. For example GitHub and the GitHub app are completely different.

**Comment by ivokwee** [comment]
will do. closed.
