### ISSUE TITLE
BrowseURL

### ISSUE THREAD

**Issue by JohnCoene** [bigomics/omicsplayground#150]
Use of `browseURL`

https://github.com/bigomics/omicsplayground/blob/919d69e9ca32244eb345e0ec261ce07e0d5d04ba/components/app/R/modules/SendReferralModule.R#L234

https://github.com/bigomics/omicsplayground/blob/919d69e9ca32244eb345e0ec261ce07e0d5d04ba/components/app/R/modules/SocialMediaModule.R#L94 

Not sure what is intended here, won't work server-side.

**Comment by ivokwee** [comment]
The idea is that if the user clicks on an icon, it goes to that social website with a predefined url and message. The reactive 'observe' is to allow detection of a real click. It's server side because we need to predefine the url.

![image](https://user-images.githubusercontent.com/19613146/167429766-cbfd8653-f6ce-43bc-90cb-b460259f860d.png)

**Comment by ivokwee** [comment]
1. OK. Timeout should not be used or be disabled at self-deployment. 
2. originally had just a tag/button
`  tags$a(href=urls["twitter"], NULL, icon("twitter"), style="font-size:35px;", target="_blank")`

**Comment by ivokwee** [comment]
So originally the button/icon bar was just like this
