### ISSUE TITLE
board description overlapping with sidebar [dev branch]

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#171]
The module description is overlapping with sidebar content on small 1366x768 laptop screens (not on big ones though). Latest chrome, deployed on latest R/Rstudio.
<p align="center">
<img width="293" alt="image" src="https://user-images.githubusercontent.com/28757711/210971399-aec24028-ff46-45e5-9fa3-aed7d36aed2e.png">
<p>

**Comment by mauromiguelm** [comment]
a possible solution could be to always at the bottom of the page (a few pixels from the bottom), so as the user scrolls down, the sidebar menu will be cleared from the board description

**Comment by ESCRI11** [comment]
Fixed in https://github.com/bigomics/bigdash/commit/9119b654eae66754d7bf8dbb34a7313fa7e3b521 now the info is at the real bottom of the page. 

Anyways, should we remove it completely @ivokwee ? I have the feeling that having the big information button at every page that triggers the info modal + this feature is redundant.
