### ISSUE TITLE
Reactivity broken ***urgent***

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#307]
Reactivity broken/hangs. No update of figures.

How to reproduce:
1. Run app using make, load example data
2. Go to expression tab, select first row of table
3. Change the contrast on the right to act12h_vs_notact
4. Plots update, and hangs after first update.

Similar on other tabs.

**Comment by ivokwee** [comment]
Could be the new spinner. Going back at "git checkout 66309b11d1db003f31ce0c2ca1a99f019226e193" (spinner commit)  I can see it worked before and hangs at this time of commit. @xavier please reproduce this error and check?

**Comment by ESCRI11** [comment]
Fixed in https://github.com/bigomics/bigLoaders/commit/7efb55be42c62c672ef4495a42640d3b5742e732

Need to use new version 0.0.2 of `bigLoaders`

### Quick recap:

`bigLoaders` was hidding the plots when displaying the loaders using `display: none` which somehow made Shiny unaware of the elements so they were not recomputed. Now using `visibility: hidden` this is solved. Probably something to do with the DOM, still looking into why other boards had no problem recomputing the plots.
