### ISSUE TITLE
dont require users to rename files to upload them

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#385]
Currently, users are required to rename files to "counts.csv", "samples.csv", and so forth before uploading them. This seems like an unnecessary step and from my experience would lead to a ton of confusion on the user's side given that files are often named in a certain way to maintain versions/dates and other important info. When a user renames their files to counts.csv, they lose important info about the file and may have trouble remembering which version of their data was used, among other things such as just being annoying to have to rename files.

It would be ideal to therefore drop this requirement. To match files to counts/samples/contrasts, users could either upload one at a time or they could upload all files and then just assign the files in a modal to the type they belong to.

**Comment by ivokwee** [comment]
It is not explained very well, but the files do not have to be exactly counts.csv, samples.csv, contrasts.csv. Any name that includes 'counts', 'samples' or 'contrasts'  will be ok. So people can upload counts_experiment1.csv or exp1_counts.csv as counts file. Same for samples and contrasts. This was done so people can have different csv in one folder, or at least annotate with some experiment label. I kind of like that you can upload 3 csv files at once, instead of one-by-one.

**Comment by ivokwee** [comment]
I am closing this. I think some convention is good.
