### ISSUE TITLE
upload module > contrasts: increase box size to allow contrast name visibility

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#457]
<img width="58" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/cfa9c982-3ddb-4ad0-aec8-8a585b88d231">

**Comment by ivokwee** [comment]
This seems to be a general problem that long names (often contrast or geneset names) in selectInput do not wrap because they have underscores. Not sure why in v2 this was less a problem. One solution is to use choiceNames and choiceValues in selectInput where in choiceNames the underscores are replaced by spaces. Another solution is to tell JS to wrap also at underscore characters. Increasing the box size is not always sufficient.
