### ISSUE TITLE
plotmodule plotoptions dropdown is clipped within card window

### ISSUE THREAD

**Issue by ivokwee** [bigomics/omicsplayground#492]
The plot options dropdown is clipped to the card window and causes the scrollbars to appear. We had this before and solved it somehow with help of Carson but now it appears again. Using some setting it should be possible to let the dropdown float and overflow outside the card borders.

![image](https://github.com/bigomics/omicsplayground/assets/19613146/ba8d43fa-0b77-40fa-876d-66b8afd43495)

**Comment by ESCRI11** [comment]
Looks to be related to the use of `bslib::layout_column_wrap`. Elements placed using traditional `col-md-X` divs do not display this behaviour (e.g. Load dataset tab)

<img width="225" alt="image" src="https://github.com/bigomics/omicsplayground/assets/10220503/524cbb11-27ca-4afd-9ba0-e9afefe83435">

Confirmed by moving elements out of `bslib::layout_column_wrap` and they automatically behave OK.

**Comment by mauromiguelm** [comment]
on it, I fixed this problem some months ago, not sure why it came back.

Investigating.

**Comment by cpsievert** [comment]
I'd be surprised if the new version of `{bslib}` did, in fact, introduce this problem. That said, with both the older and newer version of `{bslib}`, it is indeed true that, if you put a `card(style = "overflow: visible")`  in a parent element that has `overflow:auto` set (e.g., `layout_column_wrap()`) you'll run into this issue (because the parent's `overflow` setting will overrule the child's property). Here's a minimal reprex of the problem (notice how the `selectInput()`'s in the 1st row get clipped but the 2nd doesn't):

```r
library(shiny)
library(bslib)

my_card <- function() {
  card(
    style = "overflow:visible;",
    card_header(
      selectInput("foo", NULL, state.name),
      class = "d-flex justify-content-end"
    ),
    "Body"
  )
}

ui <- page_fluid(
  layout_column_wrap(
    width = 1/2,
    my_card(),
    my_card()
  ),
  my_card()
)

shinyApp(ui, function(...){})
```

You can currently work around the problem by making sure the layout containers also have `overflow: visible`, but it's definitely on my (mental) TODO list to make this sort of thing easier...

```r
layout_column_wrap_visible <- function(...) {
  res <- layout_column_wrap(..., style = "overflow:visible;")
  tagQuery(res)$children()$addAttrs(style = "overflow:visible;")$allTags()
}

ui <- page_fluid(
  layout_column_wrap_visible(
    width = 1/2,
    my_card(),
    my_card()
  ),
  my_card()
)

shinyApp(ui, function(...){})
```

**Comment by mauromiguelm** [comment]
still no effective solution, still working on it. overflow: visible breaks plots.
