### ISSUE TITLE
free.playground.bigomics.ch crashes upon "Exit"

### ISSUE THREAD

**Issue by ncullen93** [bigomics/omicsplayground#584]
After logging in at free.playground.bigomics.ch via email-link and using the app a bit, clicking "Exit" in the user dropdown on the top right logs me out I guess but crashes the entire app. Just for note, I did not load any datasets during this session.. in case this has something to do with PGX being NULL.

<img width="630" alt="Screen Shot 2023-07-17 at 12 46 16 PM" src="https://github.com/bigomics/omicsplayground/assets/13004360/e8b5cc55-51b0-4352-93e3-a0f298771d6c">

**Comment by ESCRI11** [comment]
So this is the code being triggered when 'Exit' is clicked. 

https://github.com/bigomics/omicsplayground/blob/master/components/app/R/server.R#L701-L708

What you see actually is not really an error. Perhaps we could automatically close the browser tab itself to make it better?

**Comment by ESCRI11** [comment]
Ok nevermind, JS cannot close windows that has not opened itself.

**Comment by ESCRI11** [comment]
I did a small workaround with `siever` package to get a different page.

<img width="748" alt="image" src="https://github.com/bigomics/omicsplayground/assets/10220503/7008959d-e799-4e8e-a46b-6c926c8154d3">

You can test it on this branch: https://github.com/bigomics/omicsplayground/tree/fix-%23584

**Comment by ivokwee** [comment]
guys this was intentional because session$reload would keep the session open, and I wanted the session to be freed for the next user. Also becuase without session$reload, just user logout, there were strange things happening like the next user got background jobs from the last user, or the settings from the last user were still visible to the new user. We need to be sure the previous setting are cleared cleanly. For the moment either session$reload or session$close is safe.
