### ISSUE TITLE
Missing genesets in v3.2.8-230718

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#589]
Hi,

I just noticed that in the "Geneset Enrichment" tab, the "gene set collection" scroll down menu is not displaying all the available collections (e.g. I cannot find GO, though they are still present in the table). On a similar note, what happened to the Msig C2-C7 collections? They seem to be gone and they used to be pretty informative (especially C2 and C5).

![image](https://github.com/bigomics/omicsplayground/assets/85561624/8913979d-1549-4751-8a44-bba1c1389278)

**Comment by mauromiguelm** [comment]
- C2-C7 still exist, but some of these collections had to be removed, as they had crazy stuff like a list of genes per scientist... we could bring c2-c7 from Ivo, as they have less weirdness, but I prefered to update the database and remove the weird things. I kept the important things (C2, C5...)
- GO needs a small fix in order to be show on the menu

**Comment by ivokwee** [comment]
is this meant @axel wanted C2, C3, C4, C5, C6, C7 or only C2 and C7?  I think C2,C3,C6,C7 and C8 might be interesting. C5:HPO is interesting too. C5:GO is perhaps covered by manual downloaded GO terms (true mauro?).

**Comment by mauromiguelm** [comment]
correct, we just need to understand why "go" is not showing on the table, should be an easy fix.
