### ISSUE TITLE
Find Biomarkers Module not working in v3.2.21-master230808

### ISSUE THREAD

**Issue by AxelBigOmics** [bigomics/omicsplayground#630]
I'm experiencing an issue with the Find Biomarkers module. When I try to filter samples to run the app, the "Compute" button stays unresponsive. After that it stay unresponsive even if I deselect the samples and I have to restart the platform to be able to run it without filtering samples.

![Find_biomarkers](https://github.com/bigomics/omicsplayground/assets/85561624/0fc22aae-7ead-4648-9be6-9ffdf44e8913)

**Comment by mauromiguelm** [comment]
Hi @AxelBigOmics,

It worked for me locally with example data, see below. Which dataset did you use and was it in docker or in our production server?

<img width="1130" alt="image" src="https://github.com/bigomics/omicsplayground/assets/28757711/786d3796-84a8-4ac9-b371-65008555e944">

**Comment by AxelBigOmics** [comment]
Both versions actually. I also tried different datasets. It's not the first time it froze on me either.

**Comment by mauromiguelm** [comment]
does it freeze with all datasets or with specific ones? Can you share one case with me? I need one example to work with :)

**Comment by AxelBigOmics** [comment]
I shared one with you.

**Comment by mauromiguelm** [comment]
Hi Axel, the button becomes unresponsive because we select invalid conditions to run the biomarker module. When I brought back to the original options, then it works fine.

That means you selected treatment as predicted and treatment as predictor, so that cannot work in this context. We should warn the user when the above happens, simply disabling the button is not nice.

Would a simple message when you place your mouse hover Compute button be enough?

**Comment by AxelBigOmics** [comment]
I think a warning would definitely help, as just seeing the button greyed out looks like the platform has frozen, rather then there being an issue with the selected groups

**Comment by ivokwee** [comment]
true. when selecting samples, the check is not correct. To replicate 
1. use example-data
2. Select predicted target ".celltype" (default)
3. Select both cellcycle=G1 and cellcycle=S group
4. Compute button is still disabled (should be enabled)
