### ISSUE TITLE
Tables downloaded as .htm in production (not locally)

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#637]
Some tables are being downloaded as .htm instead of .csv. One example is the table GeneSets > GeneSet enrichment > enrichment(all), which is downloaded as .htm in free.playground and as csv locally.

Its likely a js bug.

**Comment by ivokwee** [comment]
This is for @xavier. pretty nasty bug. Essentially the download link initially defaults to the host URL and downloads a html instead of image. when you click on e.g. the info button, and again on the download link, the download URL gets compiled correctly. See below. This happens both in the plotModule and tableModule. Might be related to the DropDown reimplementation.

Initial erroneous link:
![image](https://github.com/bigomics/omicsplayground/assets/19613146/32da395d-d0cb-4681-9919-df0e1db320d3)

After clicking info or else:
![image](https://github.com/bigomics/omicsplayground/assets/19613146/2ff24d15-04d4-4ee6-a36d-6a9f6ef41896)

**Comment by ivokwee** [comment]
Again, what Mauro already said. Local from source this seems not to happen. But I checked on local docker also has this bug. Even weirder, downloading the csv will reload the UI code. I have seen this in the logs too that the UI gets reloaded continously for some reason.

**Comment by mauromiguelm** [comment]
new feedback, some tables are missed: I just noticed that the same HTML issue is happening again, but this time with the "Gene signatures" UMAP plot. I tried downloading this plot, but I just got an HTML file.

**Comment by ESCRI11** [comment]
Can reproduce. Looking into it. @mauromiguelm Can you provide more context about "some tables" please?
