### ISSUE TITLE
board > tab: some tabs do not use the settings of the board and should be disables

### ISSUE THREAD

**Issue by mauromiguelm** [bigomics/omicsplayground#716]
board > tab: some tabs do not use the settings of the board and should be disabled

For example, in Expression > Diff Expr > Volcano by comparison: the settings selected contrast do not work and should be disabled.

We need to find a general solution for this problem, and fix where it happens

**Comment by ESCRI11** [comment]
Boards fixed on https://github.com/bigomics/omicsplayground/tree/fix-%23716

- [ ] board.biomarker
- [ ] board.clustering
- [ ] board.compare
- [ ] board.connectivity
- [ ] board.correlation
- [ ] board.dataview
- [ ] board.drugconnectivity
- [ ] board.enrichment
- [ ] board.expression
- [ ] board.featuremap
- [ ] board.intersection
- [ ] board.loading
- [ ] board.pathway
- [ ] board.pcsf
- [ ] board.signature
- [ ] board.singlecell
- [ ] board.tcga
- [ ] board.upload
- [ ] board.user
- [ ] board.wgcna
- [ ] board.wordcloud

**Comment by phisanti** [comment]
I have just completed the work on:

-   board.biomarker
-   board.clustering
-   board.compare
-   board.connectivity
-   board.correlation
-   board.dataview
-   board.drugconnectivity
-   board.enrichment
-   board.expression
-   board.featuremap
 
 Note that the boards expression and enrichment use all the inputs in all the panels (because the table) and drugconnectivity only has one panel.
