### ISSUE TITLE
DataView filter isn't working for gene expression 

### ISSUE THREAD

**Issue by Kstead** [bigomics/omicsplayground#811]
<details> <summary><strong>Session Info</strong></summary>
  
```r

```
</details>

Gene Expression filter isn't working with more than one filter.  For example if you filter by a cell type the add a filter by time point the graph will reset and no longer filter by cell type. It seems the filter only accepting the first phenotype then disregarding the other selected phenotype

**Comment by mauromiguelm** [comment]
@ivokwee if its simple, I will fix in both.. do you plan to release a new 3.2 or we move directly from 3.2.39 to 3.3.0?

**Comment by mauromiguelm** [comment]
Hi @Kstead 

I am studying how to approach this, there are some other improvements we can do beyond what you mentioned:

1. As you select a filter, the drop down should update with the remaining filter options.
2. Your issue is confimed, the filtering is not additive. Not sure what logic is being used right now, but we will update so it filters correctly.

**Comment by Kstead** [comment]
The Expression Tab > Find Biomarkers Subtab the filters are no longer additive as well.
