### ISSUE TITLE
[R] Use alternative for .RDS files to increase performance

### ISSUE THREAD

**Issue by stefanreifenberg** [bigomics/omicsplayground#82]
Alternatives:
data.table
https://github.com/Rdatatable/data.table

Feather:
https://github.com/wesm/feather

fst:
https://www.fstpackage.org/

arrow:
https://github.com/apache/arrow/

disk.frame
https://github.com/DiskFrame/disk.frame

**Comment by ivokwee** [comment]
Problem is that the pgx/ngs object is not just a dataframe but a big list of "anything". Can the alternatives handle different/mixed (non dataframe) datatypes? The loading time of the PGX is now within few seconds, largely by more efficient storage of large objects (GSET object: sparsematrix instead of list of character vectors).
